name: whatthehell
favicon: null
layout_spectrum: 0.9767985895741731
typography_spectrum: 0.9969670693390071
title: main page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7864028376061469
  lightness: 0.022858623880892992
  saturation: 0.8974015680141747
  rhythmicContrast: 0.1947879388462752
purpose: []
